/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PrimeAvatar: typeof import('primevue/avatar')['default']
    PrimeButton: typeof import('primevue/button')['default']
    PrimeCard: typeof import('primevue/card')['default']
    PrimeDivider: typeof import('primevue/divider')['default']
    PrimeForm: typeof import('@primevue/forms/form')['default']
    PrimeFormField: typeof import('@primevue/forms/formfield')['default']
    PrimeInputText: typeof import('primevue/inputtext')['default']
    PrimeMessage: typeof import('primevue/message')['default']
    PrimeScrollTop: typeof import('primevue/scrolltop')['default']
    PrimeTextarea: typeof import('primevue/textarea')['default']
    PrimeToast: typeof import('primevue/toast')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
